module.exports = {
  $schema: 'http://json-schema.org/draft-04/schema#',
  title: 'Code Snippet',
  type: 'object',
  properties: {
    attributes: {
      type: 'object',
      description:
        'A Drupal-style attributes object with extra attributes to append to this element.',
    },
    content: {
      type: 'any',
      description: 'Content of the code-snippet.',
    },
    lang: {
      type: 'string',
      title: 'Language',
      description: 'Language of the code text.',
      default: 'html',
      enum: [
        'markup',
        'html',
        'xml',
        'svg',
        'mathml',
        'ssml',
        'atom',
        'rss',
        'javascript',
        'js',
        'clike',
        'css',
        'scss',
        'twig',
        'java',
        'json',
        'rest',
        'bash',
        'shell',
        'csv',
        'docker',
        'dockerfile',
        'http',
        'jsx',
        'tsx',
        'md',
        'markdown',
        'yml',
        'yaml',
      ],
    },
    lang_title: {
      type: 'any',
      title: 'Language title',
      description:
        'Optional custom language title. Use default language titles whenever possible.',
    },
    syntax: {
      type: 'string',
      title: 'Syntax Highlighting',
      description:
        'Toggle between a light and dark syntax highlighting, or turn it off. Separate from Bolt theming.',
      default: 'light',
      enum: ['light', 'dark', 'none'],
    },
    hide_copy: {
      type: 'boolean',
      title: 'Hide copy to clipboard',
      description: 'Hide copy to clipboard from the toolbar.',
    },
    hide_title: {
      type: 'boolean',
      title: 'Hide language',
      description: 'Hide the language title from the toolbar.',
    },
  },
};
