const path = require('path');
const fs = require('fs-extra');

describe('Check that the bolt-starter build has compiled as expected', () => {
  test('Check that the Bolt Build Tools is generating JSON data from Sass files', async () => {
    const dataFileExists = async function(){
      try {
        await fs.promises.access(path.resolve(__dirname, "../dist/data/colors/brand.bolt.json"));
        return true;
      } catch (error) {
        return false;
      }
    }

    expect(await dataFileExists()).toBe(true);
  });

  test('Check color JSON data was generated by the build tools', async () => {
    const getColorData = async function(){
      try {
        await fs.promises.access(path.resolve(__dirname, "../dist/data/colors/brand.bolt.json"));
        const colorData = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../dist/data/colors/brand.bolt.json")));
        return colorData;
      } catch (error) {
        return false;
      }
    }

    const colorData = await getColorData();

    expect(colorData.indigo.xdark).toBe('rgb(6, 9, 35)');
    expect(colorData.yellow.base).toBe('rgb(255, 204, 77)');
  });
});
