const argv = require('yargs').argv;

module.exports = {
  env: 'drupal',
  verbosity: 1,
  enableCache: argv.prod ? false : true, // workaround to Bolt's JSON data not always getting output from Webpack
  port: 8888,
  webpackDevServer: {
    enabled: true,
  },
  buildDir: './dist',
  dataDir: './dist/data',
  wwwDir: './dist',
  publicPath: '/themes/bolt-starter/dist/',
  components: {
    global: [
      '@bolt/global',
      '@bolt/components-button',
      '@bolt/components-headline',
      '@bolt/components-link',
      '@bolt/components-icon',
      '@bolt/components-navbar',
      '@bolt/components-sticky',
      './index.scss',
      './index.js',
    ],
    individual: [
      '@bolt/components-critical-fonts',
      '@bolt/components-critical-css',
      '@bolt/components-critical-css-vars',
      '@bolt/components-carousel',
      '@bolt/global',
      '@bolt/docs-search',
      '@bolt/components-typeahead',
      // '@bolt/schema-form', // Component Explorer being temporarily disabled until we've migrated our Twig Rendering Service to Now.sh v2
      '@bolt/analytics-autolink',
      '@bolt/analytics-autotrack',
      '@bolt/components-placeholder',
      '@bolt/components-accordion',
      '@bolt/components-action-blocks',
      '@bolt/components-banner',
      '@bolt/components-dropdown',
      '@bolt/components-background',
      '@bolt/components-background-shapes',
      '@bolt/components-band',
      '@bolt/components-block-list',
      '@bolt/components-blockquote',
      '@bolt/components-breadcrumb',
      '@bolt/components-button',
      '@bolt/components-button-group',
      '@bolt/components-card',
      '@bolt/components-chip',
      '@bolt/components-chip-list',
      '@bolt/components-code-snippet',
      '@bolt/components-copy-to-clipboard',
      '@bolt/components-device-viewer',
      '@bolt/components-figure',
      '@bolt/components-form',
      '@bolt/components-headline',
      '@bolt/components-icon',
      '@bolt/components-image',
      '@bolt/components-link',
      '@bolt/components-list',
      '@bolt/components-modal',
      '@bolt/components-nav-indicator',
      '@bolt/components-nav-priority',
      '@bolt/components-navbar',
      '@bolt/components-navlink',
      '@bolt/components-logo',
      '@bolt/components-page-footer',
      '@bolt/components-page-header',
      '@bolt/components-pagination',
      '@bolt/components-share',
      '@bolt/components-search-filter',
      '@bolt/components-site',
      '@bolt/components-smooth-scroll',
      '@bolt/components-sticky',
      '@bolt/components-stack',
      '@bolt/components-table',
      '@bolt/components-tabs',
      '@bolt/components-teaser',
      '@bolt/components-text',
      '@bolt/components-tooltip',
      '@bolt/components-trigger',
      '@bolt/components-ul',
      '@bolt/components-ol',
      '@bolt/components-video',
      '@bolt/components-grid',
    ],
  },
};
