// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconCalendar(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"g","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","clip-rule":"evenodd"},"children":[{"name":"path","type":"element","value":"","attributes":{"d":"M3.9 29h24.2V12.3H3.9zM28.1 2.5h-1.4V0h-3v2.5H8.3V0h-3v2.5H3.9c-1.7 0-3 1.4-3 3V29c0 1.7 1.4 3 3 3h24.2c1.7 0 3-1.4 3-3V5.5c0-1.7-1.3-3-3-3z"},"children":[]},{"name":"path","type":"element","value":"","attributes":{"d":"M7.4 18.4h17.3v-3H7.4zM7.4 24.9H21v-3H7.4z"},"children":[]}]}]}, props);
};
