// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconCloseSolid(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","d":"M16 0C7.2 0 0 7.2 0 16s7.2 16 16 16 16-7.2 16-16S24.8 0 16 0zm5.1 19.1c.6.6.6 1.5 0 2.1-.6.6-1.5.6-2.1 0l-3-3.1-3.1 3.1c-.6.6-1.5.6-2.1 0-.6-.6-.6-1.5 0-2.1l3.1-3.1-3.1-3.1c-.6-.6-.6-1.5 0-2.1s1.5-.6 2.1 0l3.1 3.1 3.1-3.1c.6-.6 1.5-.6 2.1 0s.6 1.5 0 2.1L18.1 16z"},"children":[]}]}, props);
};
