// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconCoBrowse(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","d":"M30 12H8v-2a2 2 0 012-2h18a2 2 0 012 2zm0 16a2 2 0 01-2 2H10a2 2 0 01-2-2V14h22zM28 6H10a4 4 0 00-4 4v18a4 4 0 004 4h18a4 4 0 004-4V10a4 4 0 00-4-4zM4 2h18a2 2 0 012 2h2a4 4 0 00-4-4H4a4 4 0 00-4 4v18a4 4 0 004 4v-2a2 2 0 01-2-2V8h2V6H2V4a2 2 0 012-2z"},"children":[]}]}, props);
};
