// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconCustomerService(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","d":"M26 5.9c.8 1.2 1.4 2.6 1.7 4 1.5 1.7 2.3 3.9 2.3 6.1-.1 4-2.5 7.5-6.2 9H25v3l-3.7-2.2c-1.7.3-3.5.3-5.2-.1-1.2.2-2.4.4-3.6.4h-.7c2.2 1.3 4.7 2 7.2 2 .7 0 1.4-.1 2.1-.2L27 32v-6.5c3.1-2.2 5-5.7 5-9.5-.1-4.2-2.3-8-6-10.1M9.5 21.5L7 23v-2.6c-3-1.7-4.9-4.9-5-8.4C2 6.5 6.9 2 13 2s11 4.5 11 10-4.9 10-11 10c-1.2 0-2.4-.2-3.5-.5M26 12c0-6.6-5.8-12-13-12S0 5.4 0 12c0 3.8 1.9 7.3 5 9.5V27l4.8-3.3c1.1.2 2.1.4 3.2.4 7.2-.1 13-5.5 13-12.1"},"children":[]}]}, props);
};
