// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconEntertainment(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"g","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","clip-rule":"evenodd"},"children":[{"name":"path","type":"element","value":"","attributes":{"d":"M24.5 27h-17c-.6 0-1 .4-1 1s.4 1 1 1h17c.6 0 1-.4 1-1s-.4-1-1-1M2 6c0-.5.4-1 .9-1H29c.5 0 1 .4 1 .9V23H2zm28-3H2C.9 3 0 3.9 0 5v19c0 1.1.9 2 2 2h28c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"},"children":[]}]}]}, props);
};
