// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconFacebook(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","d":"M24.3.2v5.1h-3c-2.4 0-2.8 1.1-2.8 2.8v3.6h5.6l-.7 5.7h-4.9V32h-5.9V17.4H7.7v-5.7h4.9V7.5c0-4.9 3-7.5 7.3-7.5 1.5 0 3 .1 4.4.2z"},"children":[]}]}, props);
};
