// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconFinancial(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"g","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","clip-rule":"evenodd"},"children":[{"name":"path","type":"element","value":"","attributes":{"d":"M5 30h22V2H5zM27 0H5C3.9 0 3 .9 3 2v28c0 1.1.9 2 2 2h22c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2z"},"children":[]},{"name":"path","type":"element","value":"","attributes":{"d":"M9 10.7h14v-5H9zm-2 2h18v-9H7zM9 18.3h2v-2H9zM13 18.3h2v-2h-2zM17 18.3h2v-2h-2zM21 18.3h2v-2h-2zM9 22.3h2v-2H9zM13 22.3h2v-2h-2zM17 22.3h2v-2h-2zM21 22.3h2v-2h-2zM9 26.3h2v-2H9zM13 26.3h2v-2h-2zM17 26.3h2v-2h-2zM21 26.3h2v-2h-2z"},"children":[]}]}]}, props);
};
