// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconHeartSolid(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","d":"M16 30.7l-2.3-2.1C5.4 21.1 0 16.2 0 10.1c0-4.9 3.9-8.8 8.8-8.8 2.8 0 5.5 1.3 7.2 3.3 1.7-2 4.4-3.3 7.2-3.3 4.9 0 8.8 3.9 8.8 8.8 0 6-5.4 11-13.7 18.5z"},"children":[]}]}, props);
};
