// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconInsurance(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","d":"M2 16a14 14 0 0128 0zM16 0A16 16 0 000 16v2h14v8a6 6 0 0012 0h-2a4 4 0 01-8 0v-8h16v-2A16 16 0 0016 0z"},"children":[]}]}, props);
};
