// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconList(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"g","type":"element","value":"","attributes":{"fill":"#151619"},"children":[{"name":"path","type":"element","value":"","attributes":{"d":"M0 0h8v8H0zM0 24h8v8H0zM0 12h8v8H0zM12 26h20v4H12zM12 2h20v4H12zM12 14h20v4H12z"},"children":[]}]}]}, props);
};
