// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconLock(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","d":"M27.6 27.6c0 .8-.7 1.5-1.5 1.5H5.8c-.8 0-1.5-.7-1.5-1.5V17.5c.1-.8.7-1.5 1.5-1.5h20.4c.8 0 1.5.7 1.5 1.5v10.1zM10.2 8.7c0-3.2 2.6-5.8 5.8-5.8s5.8 2.6 5.8 5.8v4.4H10.2zm16 4.4h-1.5V8.7C24.7 3.9 20.8 0 16 0S7.3 3.9 7.3 8.7v4.4H5.8c-2.4 0-4.4 2-4.4 4.4v10.2c0 2.4 2 4.4 4.4 4.4h20.4c2.4 0 4.4-2 4.4-4.4V17.5c-.1-2.5-2-4.4-4.4-4.4z","clip-rule":"evenodd"},"children":[]}]}, props);
};
