// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconMenu(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"g","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","clip-rule":"evenodd"},"children":[{"name":"path","type":"element","value":"","attributes":{"d":"M30.4 14.4H1.6c-.9 0-1.6.7-1.6 1.6s.7 1.6 1.6 1.6h28.8c.9 0 1.6-.7 1.6-1.6s-.7-1.6-1.6-1.6M1.6 6.4h28.8c.9 0 1.6-.7 1.6-1.6s-.7-1.6-1.6-1.6H1.6C.7 3.2 0 3.9 0 4.8s.7 1.6 1.6 1.6M30.4 25.6H1.6c-.9 0-1.6.7-1.6 1.6s.7 1.6 1.6 1.6h28.8c.9 0 1.6-.7 1.6-1.6s-.7-1.6-1.6-1.6"},"children":[]}]}]}, props);
};
