// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconMinusCircle(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"g","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","clip-rule":"evenodd"},"children":[{"name":"path","type":"element","value":"","attributes":{"d":"M16 29.1C8.8 29.1 2.9 23.2 2.9 16S8.8 2.9 16 2.9 29.1 8.8 29.1 16 23.2 29.1 16 29.1M16 0C7.2 0 0 7.2 0 16s7.2 16 16 16 16-7.2 16-16S24.8 0 16 0"},"children":[]},{"name":"path","type":"element","value":"","attributes":{"d":"M21.8 14.5l-11.6.1c-.8 0-1.5.7-1.5 1.5s.7 1.5 1.5 1.5H22c.8 0 1.5-.7 1.5-1.5s-.9-1.6-1.7-1.6"},"children":[]}]}]}, props);
};
