// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconMinus(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","d":"M2.9 13.9c-1.1 0-2 .9-2 2.1s.9 2.1 2 2.1h26.2c1.1 0 2-.9 2-2.1s-.9-2.1-2-2.1z","clip-rule":"evenodd"},"children":[]}]}, props);
};
