// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconMinusSolid(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","d":"M16 0C7.2 0 0 7.2 0 16s7.2 16 16 16 16-7.2 16-16S24.8 0 16 0zm5.8 17.5H10c-.8 0-1.5-.7-1.5-1.5s.7-1.5 1.5-1.5h11.8c.8 0 1.5.7 1.5 1.5s-.7 1.5-1.5 1.5z"},"children":[]}]}, props);
};
