// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconMobility(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","d":"M14.6 27.4c-.7-.6-.8-1.7-.2-2.4.4-.8 1.5-1.1 2.3-.7.9.2 1.4 1.2 1.2 2.1-.1 1-.7 1.5-1.8 1.6-.6.1-1.1-.2-1.5-.6zM24 22H8v6c0 .5.2 1.1.6 1.4.4.4.9.6 1.4.6h12c.5 0 1.1-.2 1.4-.6.4-.4.6-.9.6-1.4zm0-18c0-.5-.2-1.1-.6-1.4-.4-.4-.9-.6-1.4-.6H10c-.5 0-1.1.2-1.4.6C8.2 3 8 3.5 8 4v16h16zm2 0v24c-.1 2.2-1.8 3.9-4 4H10c-1.1 0-2.1-.4-2.8-1.2C6.4 30.1 6 29.1 6 28V4c0-1.1.4-2.1 1.2-2.8C7.9.4 8.9 0 10 0h12c1.1 0 2.1.4 2.8 1.2.8.7 1.2 1.7 1.2 2.8z","clip-rule":"evenodd"},"children":[]}]}, props);
};
