// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconPegaSort(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"g","type":"element","value":"","attributes":{"fill":"#151619"},"children":[{"name":"path","type":"element","value":"","attributes":{"d":"M26 8.6L18.3.9C17.7.3 16.9 0 16 0s-1.7.3-2.3.9L6 8.6c-.9.9-1.2 2.3-.7 3.5s1.7 2 3 2h15.4c1.3 0 2.5-.8 3-2s.2-2.5-.7-3.5zm-2.8 2.2c-.3.8-1.1 1.3-2 1.3H10.8c-.9 0-1.7-.5-2-1.3-.4-.9-.2-1.8.4-2.4l5.2-5.2c.4-.4 1-.6 1.5-.6.6 0 1.1.2 1.5.6l5.2 5.2c.8.6 1 1.5.6 2.4zM6 23.4l7.7 7.7c.6.6 1.4.9 2.3.9s1.7-.3 2.3-.9l7.7-7.7c.9-.9 1.2-2.3.7-3.5s-1.7-2-3-2H8.3c-1.3 0-2.5.8-3 2s-.2 2.5.7 3.5zm2.8-2.2c.3-.8 1.1-1.3 2-1.3h10.4c.9 0 1.7.5 2 1.3.4.9.2 1.8-.4 2.4l-5.2 5.2c-.4.4-1 .6-1.5.6-.6 0-1.1-.2-1.5-.6l-5.2-5.2c-.8-.6-1-1.5-.6-2.4z"},"children":[]}]}]}, props);
};
