// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconPlatform(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","fill-rule":"evenodd","d":"M16 2L0 10l16 8 16-8zM4 9.8L16 4l12 5.8L16 16zM27.5 16L16 22 4.5 16H0l16 8 16-8zm0 6L16 28 4.5 22H0l16 8 16-8z","clip-rule":"evenodd"},"children":[]}]}, props);
};
