// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconReply(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","d":"M12.4 9.8V2.7L0 15.1l12.4 12.4v-7.3c8.9 0 15.1 2.8 19.6 9.1-1.8-8.9-7.1-17.7-19.6-19.5z"},"children":[]}]}, props);
};
