// THIS IS AN AUTOGENERATED FILE
import { getSvg } from '../../icon-lib';
export function iconStarSolid(props) {
  return getSvg({"name":"svg","type":"element","value":"","attributes":{"xmlns":"http://www.w3.org/2000/svg","viewBox":"0 0 32 32"},"children":[{"name":"path","type":"element","value":"","attributes":{"fill":"#151619","d":"M22.1 19.6l9.9-7.2H19.8L16 .8l-3.8 11.6H0l9.9 7.2-3.8 11.6L16 24l9.9 7.2z"},"children":[]}]}, props);
};
