<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1eb16d3ec36b85a9e75ab0abd293b8d4
{
    public static $files = array (
        '7f6424204c72ddd18b41674c404b34dd' => __DIR__ . '/..' . '/lostkobrakai/frctl-twig/src/Twig.php',
    );

    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twig\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' => 
        array (
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
    );

    public static $classMap = array (
        'Alias_Loader' => __DIR__ . '/..' . '/lostkobrakai/frctl-twig/src/Loader.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1eb16d3ec36b85a9e75ab0abd293b8d4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1eb16d3ec36b85a9e75ab0abd293b8d4::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit1eb16d3ec36b85a9e75ab0abd293b8d4::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit1eb16d3ec36b85a9e75ab0abd293b8d4::$classMap;

        }, null, ClassLoader::class);
    }
}
